### ISSUE TITLE
sumominer.py not running on ubuntu 17.04

### ISSUE THREAD

**Issue by yeahia2508** [sumoprojects/SumoEasyMiner#10]
python sumominer.py  command giving exception :
 
    Traceback (most recent call last):
	  File "sumominer.py", line 10, in <module>
	    from main import main
	  File "/home/y34h1a/Downloads/SumoEasyMiner/main.py", line 10, in <module>
	    from app.QSingleApplication import QSingleApplication
	  File "/home/y34h1a/Downloads/SumoEasyMiner/app/QSingleApplication.py", line 58
	    except Exception, err:
		            ^
	SyntaxError: invalid syntax

**Comment by zausnerd** [comment]
I think you need to run sumominer.py with python 2, not python 3. You can check your version by running 
```
python --version
```

**Comment by Tan-tan-san** [comment]
I've run it with python2 and python 3 with the same results.
 >> python --version
Python 2.7.6

Traceback (most recent call last):
  File "sumominer.py", line 10, in <module>
    from main import main
  File "/home/chase/SumoEasyMiner/main.py", line 10, in <module>
    from app.QSingleApplication import QSingleApplication
  File "/home/chase/SumoEasyMiner/app/QSingleApplication.py", line 12, in <module>
    from PySide.QtGui import QApplication
ImportError: No module named PySide.QtGui

**Comment by zausnerd** [comment]
@Tan-tan-san , that would be a different issue. The error is saying you need the PySide module. You can take a look at [https://pypi.python.org/pypi/PySide](https://pypi.python.org/pypi/PySide), that will give you instructions on installing based on your OS.

**Comment by yeahia2508** [comment]
I also teseted in python 2 but same issue like before.

**Comment by zausnerd** [comment]
@yeahia2508  If you run 
``` python2  sumominer.py```, what error do you see?

**Comment by canteboi** [comment]
i encountered this one also, even when using python2

`python2 sumominer.py `

```
Traceback (most recent call last):
  File "sumominer.py", line 10, in <module>
    from main import main
  File "/home/xx/gitprojects/SumoEasyMiner/main.py", line 10, in <module>
    from app.QSingleApplication import QSingleApplication
  File "/home/xx/gitprojects/SumoEasyMiner/app/QSingleApplication.py", line 12, in <module>
    from PySide.QtGui import QApplication
ImportError: No module named PySide.QtGui
```

`python --version`

`Python 2.7.12`

**Comment by noraj** [comment]
1) Using PySide for Qt bindings is a bad idea because it's officially a [dead](https://pyqt.developpez.com/actu/80721/Le-projet-PySide-est-declare-abandonne-en-2015-il-ne-reste-plus-que-PyQt-comme-binding-Python-de-Qt/) project. Use [PyQt](https://riverbankcomputing.com/software/pyqt/intro) instead.

2) Using PySide for Qt bindings is a bad idea because it's doesn't support python 3.5 and 3.6.

```
$ sudo pip install pyside

Collecting pyside
  Downloading PySide-1.2.4.tar.gz (9.3MB)
    100% |████████████████████████████████| 9.3MB 133kB/s
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jd4etxjc/pyside/

$ python --version
Python 3.6.4
```

**Comment by ghost** [comment]
I need step by step method to build it in ubuntu, am kind of confused

**Comment by pangdiin** [comment]
This is hard to set up in linux, there is no proper guide WTF!!

**Comment by ghost** [comment]
Everything is possible, there is a way

**Comment by Moogly** [comment]
Use apt-get to install pyside and psutil:

```
sudo apt-get install python-pyside python-psutil
```
Lastly you'll need the cryptonite_hash library. Idk why the devs didn't just use tk for the UI it's not like this UI is all that fancy and tk has better support throughout Python and is easy to install.
