### ISSUE TITLE
Error in ubuntu 16.04 in starting

### ISSUE THREAD

**Issue by Gujjar95** [sumoprojects/SumoEasyMiner#14]
Hello Guys,
I followed all the instruction given by you but when starting `python sumominer.py` i am getting error.
`Traceback (most recent call last):
  File "sumominer.py", line 10, in <module>
    from main import main
  File "/home/gujjar/SumoEasyMiner/main.py", line 16, in <module>
    from app.hub import Hub
  File "/home/gujjar/SumoEasyMiner/app/hub.py", line 18, in <module>
    from ui import AddPoolDialog
  File "/home/gujjar/SumoEasyMiner/ui/__init__.py", line 25, in <module>
    from miner.miner import MinerWork, MinerRPC, human_readable_hashrate
  File "/home/gujjar/SumoEasyMiner/miner/miner.py", line 16, in <module>
    from libs import cpu_has_aes_in_supported, cryptolite_hash, cryptonite_hash
  File "/home/gujjar/SumoEasyMiner/libs/__init__.py", line 5, in <module>
    from cryptonite_hash import cpu_has_aes_in_supported, cryptolite_hash, cryptonite_hash
ImportError: /home/gujjar/SumoEasyMiner/libs/cryptonite_hash.so: undefined symbol: _Py_FalseStruct
`

**Comment by CattleOfRa** [comment]
I am getting this error also. I have followed every step correctly and have tried researching but without any solution to this problem.

**Comment by pangdiin** [comment]
I am getting this error, can someone help

**Comment by juansolana** [comment]
I'm getting this error as well, was anyone able to solve it?

**Comment by shabby748** [comment]
I am getting the error，can anyone fix it？
