### ISSUE TITLE
ImportError: No module named PySide.QtGui

### ISSUE THREAD

**Issue by fabriek-huis** [sumoprojects/SumoEasyMiner#6]
```
git clone https://github.com/sumoprojects/SumoEasyMiner SumoEasyMiner
cd sumoeasyminer
python sumominer.py
```

# output

```
Traceback (most recent call last):
  File "sumominer.py", line 10, in <module>
    from main import main
  File "/SumoEasyMiner/main.py", line 10, in <module>
    from app.QSingleApplication import QSingleApplication
  File "/SumoEasyMiner/app/QSingleApplication.py", line 12, in <module>
    from PySide.QtGui import QApplication
ImportError: No module named PySide.QtGui
:sumoeasyminer$ 
```

# error 
>>> `ImportError: No module named PySide.QtGui`

**Comment by havocesp** [comment]
Solved the same error from a Debian "testing". Just install PySide.QtGui package using apt-get ....

`sudo apt-get install python-pyside`
